### ISSUE TITLE
hexo server 本地无法访问categories

### ISSUE THREAD

**Issue by Arondight** [Arondight/arondight.github.io#1]
``` text
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at /home/ispeller/Repo/arondight.github.io/node_modules/hexo-server/lib/middlewares/route.js:27:11
    at call (/home/ispeller/Repo/arondight.github.io/node_modules/hexo-server/node_modules/connect/index.js:239:7)
    at next (/home/ispeller/Repo/arondight.github.io/node_modules/hexo-server/node_modules/connect/index.js:183:5)
    at compression (/home/ispeller/Repo/arondight.github.io/node_modules/hexo-server/node_modules/compression/index.js:218:5)
    at call (/home/ispeller/Repo/arondight.github.io/node_modules/hexo-server/node_modules/connect/index.js:239:7)
    at next (/home/ispeller/Repo/arondight.github.io/node_modules/hexo-server/node_modules/connect/index.js:183:5)
    at /home/ispeller/Repo/arondight.github.io/node_modules/hexo-server/lib/middlewares/header.js:6:5
    at call (/home/ispeller/Repo/arondight.github.io/node_modules/hexo-server/node_modules/connect/index.js:239:7)
    at next (/home/ispeller/Repo/arondight.github.io/node_modules/hexo-server/node_modules/connect/index.js:183:5)
    at Function.handle (/home/ispeller/Repo/arondight.github.io/node_modules/hexo-server/node_modules/connect/index.js:186:3)
    at Server.app (/home/ispeller/Repo/arondight.github.io/node_modules/hexo-server/node_modules/connect/index.js:51:37)
    at emitTwo (events.js:100:13)
    at Server.emit (events.js:185:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:537:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
```

> **Github Pages 上能够访问正常**

**Comment by Arondight** [comment]
现象同[hexo #1746](https://github.com/hexojs/hexo/issues/1746)。

**Comment by Arondight** [comment]
Duplicate of https://github.com/hexojs/hexo/issues/1746
