### ISSUE TITLE
hexo 部分参数提示未注册

### ISSUE THREAD

**Issue by Arondight** [Arondight/arondight.github.io#2]
一个示例输出如下：

``` text
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Console `help` has not been registered yet!
    at /home/ispeller/Repo/arondight.github.io/node_modules/hexo/lib/hexo/index.js:194:14
    at Promise._execute (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at Hexo.call (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/lib/hexo/index.js:188:10)
    at runHexoCommand (/usr/lib/node_modules/hexo/node_modules/hexo-cli/lib/index.js:58:17)
    at tryCatcher (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

`packages.json` 如下（同样适用于#1）：

``` json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.2.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-cli": "^1.0.1",
    "hexo-deployer-git": "0.0.4",
    "hexo-generator-archive": "^0.1.2",
    "hexo-generator-baidu-sitemap": "^0.1.2",
    "hexo-generator-category": "^0.1.2",
    "hexo-generator-feed": "^1.0.3",
    "hexo-generator-index": "^0.1.3",
    "hexo-generator-sitemap": "^1.1.2",
    "hexo-generator-tag": "^0.1.1",
    "hexo-renderer-ejs": "^0.1.1",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.1.2"
  }
}
```

**Comment by Arondight** [comment]
已提交[hexo #1796](https://github.com/hexojs/hexo/issues/1796)
